package uk.ac.ebi.pride.gui.utils;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Map;

import org.junit.Test;

import uk.ac.ebi.pride.gui.component.sequence.Protein;
import junit.framework.TestCase;

public class ProteinNameFetcherTest extends TestCase {
	private ProteinDetailFetcher fetcher = new ProteinDetailFetcher();

	protected void setUp() throws Exception {
		super.setUp();
	}

	@Test
	public void testGetUniProtDetails() {
		String accession = "P12345";
		
		try {
			Protein p = fetcher.getProteinDetails(accession);
			
			assertNotNull(p);
			assertEquals("P12345", p.getAccession());
			assertEquals("Aspartate aminotransferase, mitochondrial (mAspAT) (EC 2.6.1.1) (Fatty acid-binding protein) (FABP-1) (Glutamate oxaloacetate transaminase 2) (Plasma membrane-associated fatty acid-binding protein) (FABPpm) (Transaminase A) (Fragment)", p.getName());
			assertEquals("SSWWAHVEMGPPDPILGVTEAYKRDTNSKK", p.getSequenceString());
		} catch (Exception e) {
			fail(e.getMessage());
		}		
	}
	
	@Test
	public void testGetIpiDetails() {
		String accession = "IPI00003881";
		try {
			Protein p = fetcher.getProteinDetails(accession);
			
			assertNotNull(p);
			assertEquals(accession, p.getAccession());
			assertEquals("HETEROGENEOUS NUCLEAR RIBONUCLEOPROTEIN F.", p.getName());
			assertEquals("MMLGPEGGEGFVVKLRGLPWSCSVEDVQNFLSDCTIHDGAAGVHFIYTREGRQSGEAFVELGSEDDVKMALKKDRESMGHRYIEVFKSHRTEMDWVLKHSGPNSADSANDGFVRLRGLPFGCTKEEIVQFFSGLEIVPNGITLPVDPEGKITGEAFVQFASQELAEKALGKHKERIGHRYIEVFKSSQEEVRSYSDPPLKFMSVQRPGPYDRPGTARRYIGIVKQAGLERMRPGAYSTGYGGYEEYSGLSDGYGFTTDLFGRDLSYCLSGMYDHRYGDSEFTVQSTTGHCVHMRGLPYKATENDIYNFFSPLNPVRVHIEIGPDGRVTGEADVEFATHEEAVAAMSKDRANMQHRYIELFLNSTTGASNGAYSSQVMQGMGVSAAQATYSGLESQSVSGCYGAGYSGQNSMGGYD", p.getSequenceString());
		}
		catch (Exception e) {
			fail(e.getMessage());
		}
	}
	
	@Test
	public void testGetNcbiIdDetails() {
		String id = "120666";
		try {
			Protein p = fetcher.getProteinDetails(id);
			
			assertNotNull(p);
			assertEquals(id, p.getAccession());
			assertEquals("Glyceraldehyde-3-phosphate dehydrogenase, cytosolic", p.getName());
			assertEquals("MAPIKIGINGFGRIGRLVARVALQRDDVELVAVNDPFISTDYMTYMFKYDSVHGAWKHHELKVKDEKTLLFGEKPVVVFGRRNPEEIPRASTGAEYIVESTGVFTDKDKAAAHLKGGAKKVIISAPSKDAPMFVVGVNEKEYKSDLHIVSNASCTTNCLAPLAKVINDRFGIVEGLMTTVHSITATQKTVDGPSAKDWRGGRAASFNIIPSSTGAAKAVGKVLPQLNGKLTGMSFRVPTVDVSVVDLTVRLEKKATYEQIKAAIKEESEGKLKGILGYTEDDVVSTDFVGDSRSSIFDAKAGIALNDNFVKLVSWYDNEWGYSTRVVDLIVHMASVQ", p.getSequenceString());
		}
		catch (Exception e) {
			fail(e.getMessage());
		}
	}
	
	@Test
	public void testGetEnsemblDetails() {
		String accession = "ENSP00000263100";
		try {
			Protein p = fetcher.getProteinDetails(accession);
			
			assertNotNull(p);
			assertEquals(accession, p.getAccession());
			assertEquals("Alpha-1B-glycoprotein (Alpha-1-B glycoprotein)", p.getName());
			assertEquals("MSMLVVFLLLWGVTWGPVTEAAIFYETQPSLWAESESLLKPLANVTLTCQAHLETPDFQLFKNGVAQEPVHLDSPAIKHQFLLTGDTQGRYRCRSGLSTGWTQLSKLLELTGPKSLPAPWLSMAPVSWITPGLKTTAVCRGVLRGVTFLLRREGDHEFLEVPEAQEDVEATFPVHQPGNYSCSYRTDGEGALSEPSATVTIEELAAPPPPVLMHHGESSQVLHPGNKVTLTCVAPLSGVDFQLRRGEKELLVPRSSTSPDRIFFHLNAVALGDGGHYTCRYRLHDNQNGWSGDSAPVELILSDETLPAPEFSPEPESGRALRLRCLAPLEGARFALVREDRGGRRVHRFQSPAGTEALFELHNISVADSANYSCVYVDLKPPFGGSAPSERLELHVDGPPPRPQLRATWSGAVLAGRDAVLRCEGPIPDVTFELLREGETKAVKTVRTPGAAANLELIFVGPQHAGNYRCRYRSWVPHTFESELSDPVELLVAES", p.getSequenceString());
		}
		catch (Exception e) {
			fail(e.getMessage());
		}
	}
	
	@Test
	public void testGetRefseqDetails() {
		String accession = "NP_004788";
		try {
			Protein p = fetcher.getProteinDetails(accession);
			
			assertNotNull(p);
			assertEquals(accession, p.getAccession());
			assertEquals("adiponectin precursor [Homo sapiens]", p.getName());
			assertEquals("MLLLGAVLLLLALPGHDQETTTQGPGVLLPLPKGACTGWMAGIPGHPGHNGAPGRDGRDGTPGEKGEKGDPGLIGPKGDIGETGVPGAEGPRGFPGIQGRKGEPGEGAYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCNIPGLYYFAYHITVYMKDVKVSLFKKDKAMLFTYDQYQENNVDQASGSVLLHLEVGDQVWLQVYGEGERNGLYADNDNDSTFTGFLLYHDTN", p.getSequenceString());
		}
		catch (Exception e) {
			fail(e.getMessage());
		}
	}
	
	@Test
	public void testGetProtDetailsCollection() {
		ArrayList<String> accessions = new ArrayList<String>(3);
		accessions.add("P12345");
		accessions.add("P12346");
		accessions.add("P12347");
		accessions.add("TRFE_RAT"); // id for P12346
		accessions.add("IPI00003881");
		accessions.add("ENSP00000263100");
		accessions.add("NP_004788");
		accessions.add("120666");
		accessions.add("157327346");
		
		try {
			Map<String, Protein> proteins = fetcher.getProteinDetails(accessions);
			
			assertEquals(9, proteins.size());
			
			Protein p = proteins.get("P12345");
			assertNotNull(p);
			assertEquals("P12345", p.getAccession());
			assertEquals("Aspartate aminotransferase, mitochondrial (mAspAT) (EC 2.6.1.1) (Fatty acid-binding protein) (FABP-1) (Glutamate oxaloacetate transaminase 2) (Plasma membrane-associated fatty acid-binding protein) (FABPpm) (Transaminase A) (Fragment)", p.getName());
			assertEquals("SSWWAHVEMGPPDPILGVTEAYKRDTNSKK", p.getSequenceString());
			
			p = proteins.get("TRFE_RAT");
			assertNotNull(p);
			assertEquals("P12346", p.getAccession());
			assertEquals("Serotransferrin (Transferrin) (Beta-1 metal-binding globulin) (Liver regeneration-related protein LRRG03) (Siderophilin)", p.getName());
			assertEquals("MRFAVGALLACAALGLCLAVPDKTVKWCAVSEHENTKCISFRDHMKTVLPADGPRLACVKKTSYQDCIKAISGGEADAITLDGGWVYDAGLTPNNLKPVAAEFYGSLEHPQTHYLAVAVVKKGTDFQLNQLQGKKSCHTGLGRSAGWIIPIGLLFCNLPEPRKPLEKAVASFFSGSCVPCADPVAFPQLCQLCPGCGCSPTQPFFGYVGAFKCLRDGGGDVAFVKHTTIFEVLPQKADRDQYELLCLDNTRKPVDQYEDCYLARIPSHAVVARNGDGKEDLIWEILKVAQEHFGKGKSKDFQLFGSPLGKDLLFKDSAFGLLRVPPRMDYRLYLGHSYVTAIRNQREGVCPEGSIDSAPVKWCALSHQERAKCDEWSVSSNGQIECESAESTEDCIDKIVNGEADAMSLDGGHAYIAGQCGLVPVMAENYDISSCTNPQSDVFPKGYYAVAVVKASDSSINWNNLKGKKSCHTGVDRTAGWNIPMGLLFSRINHCKFDEFFSQGCAPGYKKNSTLCDLCIGPAKCAPNNREGYNGYTGAFQCLVEKGDVAFVKHQTVLENTNGKNTAAWAKDLKQEDFQLLCPDGTKKPVTEFATCHLAQAPNHVVVSRKEKAARVSTVLTAQKDLFWKGDKDCTGNFCLFRSSTKDLLFRDDTKCLTKLPEGTTYEEYLGAEYLQAVGNIRKCSTSRLLEACTFHKS", p.getSequenceString());
			
			p = proteins.get("P12346");
			assertNotNull(p);
			assertEquals("P12346", p.getAccession());
			assertEquals("Serotransferrin (Transferrin) (Beta-1 metal-binding globulin) (Liver regeneration-related protein LRRG03) (Siderophilin)", p.getName());
			assertEquals("MRFAVGALLACAALGLCLAVPDKTVKWCAVSEHENTKCISFRDHMKTVLPADGPRLACVKKTSYQDCIKAISGGEADAITLDGGWVYDAGLTPNNLKPVAAEFYGSLEHPQTHYLAVAVVKKGTDFQLNQLQGKKSCHTGLGRSAGWIIPIGLLFCNLPEPRKPLEKAVASFFSGSCVPCADPVAFPQLCQLCPGCGCSPTQPFFGYVGAFKCLRDGGGDVAFVKHTTIFEVLPQKADRDQYELLCLDNTRKPVDQYEDCYLARIPSHAVVARNGDGKEDLIWEILKVAQEHFGKGKSKDFQLFGSPLGKDLLFKDSAFGLLRVPPRMDYRLYLGHSYVTAIRNQREGVCPEGSIDSAPVKWCALSHQERAKCDEWSVSSNGQIECESAESTEDCIDKIVNGEADAMSLDGGHAYIAGQCGLVPVMAENYDISSCTNPQSDVFPKGYYAVAVVKASDSSINWNNLKGKKSCHTGVDRTAGWNIPMGLLFSRINHCKFDEFFSQGCAPGYKKNSTLCDLCIGPAKCAPNNREGYNGYTGAFQCLVEKGDVAFVKHQTVLENTNGKNTAAWAKDLKQEDFQLLCPDGTKKPVTEFATCHLAQAPNHVVVSRKEKAARVSTVLTAQKDLFWKGDKDCTGNFCLFRSSTKDLLFRDDTKCLTKLPEGTTYEEYLGAEYLQAVGNIRKCSTSRLLEACTFHKS", p.getSequenceString());
			
			p = proteins.get("IPI00003881");
			assertNotNull(p);
			assertEquals("IPI00003881.5", p.getAccession());
			assertEquals("HETEROGENEOUS NUCLEAR RIBONUCLEOPROTEIN F.", p.getName());
			assertEquals("MMLGPEGGEGFVVKLRGLPWSCSVEDVQNFLSDCTIHDGAAGVHFIYTREGRQSGEAFVELGSEDDVKMALKKDRESMGHRYIEVFKSHRTEMDWVLKHSGPNSADSANDGFVRLRGLPFGCTKEEIVQFFSGLEIVPNGITLPVDPEGKITGEAFVQFASQELAEKALGKHKERIGHRYIEVFKSSQEEVRSYSDPPLKFMSVQRPGPYDRPGTARRYIGIVKQAGLERMRPGAYSTGYGGYEEYSGLSDGYGFTTDLFGRDLSYCLSGMYDHRYGDSEFTVQSTTGHCVHMRGLPYKATENDIYNFFSPLNPVRVHIEIGPDGRVTGEADVEFATHEEAVAAMSKDRANMQHRYIELFLNSTTGASNGAYSSQVMQGMGVSAAQATYSGLESQSVSGCYGAGYSGQNSMGGYD", p.getSequenceString());
			
			p = fetcher.getProteinDetails("ENSP00000263100");
			assertNotNull(p);
			assertEquals("ENSP00000263100", p.getAccession());
			assertEquals("Alpha-1B-glycoprotein (Alpha-1-B glycoprotein)", p.getName());
			assertEquals("MSMLVVFLLLWGVTWGPVTEAAIFYETQPSLWAESESLLKPLANVTLTCQAHLETPDFQLFKNGVAQEPVHLDSPAIKHQFLLTGDTQGRYRCRSGLSTGWTQLSKLLELTGPKSLPAPWLSMAPVSWITPGLKTTAVCRGVLRGVTFLLRREGDHEFLEVPEAQEDVEATFPVHQPGNYSCSYRTDGEGALSEPSATVTIEELAAPPPPVLMHHGESSQVLHPGNKVTLTCVAPLSGVDFQLRRGEKELLVPRSSTSPDRIFFHLNAVALGDGGHYTCRYRLHDNQNGWSGDSAPVELILSDETLPAPEFSPEPESGRALRLRCLAPLEGARFALVREDRGGRRVHRFQSPAGTEALFELHNISVADSANYSCVYVDLKPPFGGSAPSERLELHVDGPPPRPQLRATWSGAVLAGRDAVLRCEGPIPDVTFELLREGETKAVKTVRTPGAAANLELIFVGPQHAGNYRCRYRSWVPHTFESELSDPVELLVAES", p.getSequenceString());
			
			p = fetcher.getProteinDetails("NP_004788");
			assertNotNull(p);
			assertEquals("NP_004788", p.getAccession());
			assertEquals("adiponectin precursor [Homo sapiens]", p.getName());
			assertEquals("MLLLGAVLLLLALPGHDQETTTQGPGVLLPLPKGACTGWMAGIPGHPGHNGAPGRDGRDGTPGEKGEKGDPGLIGPKGDIGETGVPGAEGPRGFPGIQGRKGEPGEGAYVYRSAFSVGLETYVTIPNMPIRFTKIFYNQQNHYDGSTGKFHCNIPGLYYFAYHITVYMKDVKVSLFKKDKAMLFTYDQYQENNVDQASGSVLLHLEVGDQVWLQVYGEGERNGLYADNDNDSTFTGFLLYHDTN", p.getSequenceString());
			
			p = fetcher.getProteinDetails("120666");
			assertNotNull(p);
			assertEquals("120666", p.getAccession());
			assertEquals("Glyceraldehyde-3-phosphate dehydrogenase, cytosolic", p.getName());
			assertEquals("MAPIKIGINGFGRIGRLVARVALQRDDVELVAVNDPFISTDYMTYMFKYDSVHGAWKHHELKVKDEKTLLFGEKPVVVFGRRNPEEIPRASTGAEYIVESTGVFTDKDKAAAHLKGGAKKVIISAPSKDAPMFVVGVNEKEYKSDLHIVSNASCTTNCLAPLAKVINDRFGIVEGLMTTVHSITATQKTVDGPSAKDWRGGRAASFNIIPSSTGAAKAVGKVLPQLNGKLTGMSFRVPTVDVSVVDLTVRLEKKATYEQIKAAIKEESEGKLKGILGYTEDDVVSTDFVGDSRSSIFDAKAGIALNDNFVKLVSWYDNEWGYSTRVVDLIVHMASVQ", p.getSequenceString());
		}
		catch(Exception e) {
			e.printStackTrace();
			fail(e.getMessage());
		}
	}
	
	@Test
	public void testMergedUniprotAccessions() {
		ArrayList<String> accessions = new ArrayList<String>(3);
		accessions.add("O88541");
		
		try {
			Map<String, Protein> proteins = fetcher.getProteinDetails(accessions);
			
			assertEquals(2, proteins.size());
			Protein p = proteins.get("O88541");
			assertNotNull(p);
			assertEquals("P24368", p.getAccession());
			assertEquals("Peptidyl-prolyl cis-trans isomerase B (PPIase B) (EC 5.2.1.8) (CYP-S1) (Cyclophilin B) (Rotamase B) (S-cyclophilin) (SCYLP)", p.getName());
			assertEquals("MLRLSERNMKVLFAAALIVGSVVFLLLPGPSVANDKKKGPKVTVKVYFDFQIGDEPVGRVTFGLFGKTVPKTVDNFVALATGEKGFGYKNSKFHRVIKDFMIQGGDFTRGDGTGGKSIYGERFPDENFKLKHYGPGWVSMANAGKDTNGSQFFITTVKTSWLDGKHVVFGKVLEGMDVVRKVENTKTDSRDKPLKDVIIVDCGKIEVEKPFAIAKE", p.getSequenceString());
		}
		catch(Exception e) {
			e.printStackTrace();
			fail(e.getMessage());
		}
	}
}
