//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.16 at 10:28:41 AM GMT 
//


package uk.ac.ebi.pride.data.jaxb.pridexml;

import uk.ac.ebi.pride.data.jaxb.pridexml.adapter.SpectrumAdapter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * The method of precursor ion selection and activation
 * 
 * <p>Java class for precursorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="precursorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ionSelection" type="{}paramType"/>
 *         &lt;element name="activation" type="{}paramType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="msLevel" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="spectrumRef" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "precursorType", propOrder = {
    "ionSelection",
    "activation"
})
public class PrecursorType {

    @XmlElement(required = true)
    protected ParamType ionSelection;
    @XmlElement(required = true)
    protected ParamType activation;
    @XmlAttribute(required = true)
    protected int msLevel;
    @XmlAttribute(required = true, name="spectrumRef")
    @XmlJavaTypeAdapter(SpectrumAdapter.class)
    protected SpectrumType spectrum;

    /**
     * Gets the value of the ionSelection property.
     * 
     * @return
     *     possible object is
     *     {@link ParamType }
     *     
     */
    public ParamType getIonSelection() {
        return ionSelection;
    }

    /**
     * Sets the value of the ionSelection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamType }
     *     
     */
    public void setIonSelection(ParamType value) {
        this.ionSelection = value;
    }

    /**
     * Gets the value of the activation property.
     * 
     * @return
     *     possible object is
     *     {@link ParamType }
     *     
     */
    public ParamType getActivation() {
        return activation;
    }

    /**
     * Sets the value of the activation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamType }
     *     
     */
    public void setActivation(ParamType value) {
        this.activation = value;
    }

    /**
     * Gets the value of the msLevel property.
     * 
     */
    public int getMsLevel() {
        return msLevel;
    }

    /**
     * Sets the value of the msLevel property.
     * 
     */
    public void setMsLevel(int value) {
        this.msLevel = value;
    }

    /**
     * Gets the value of the spectrumRef property.
     * 
     */
    public SpectrumType getSpectrum() {
        return spectrum;
    }

    /**
     * Sets the value of the spectrumRef property.
     * 
     */
    public void setSpectrum(SpectrumType spec) {
        this.spectrum = spec;
    }

}
